

#Host Port
server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/  
      
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: service-product
          uri: lb://service-product
          predicates:
          - Path=/products/**
        - id: service-user
          uri: lb://service-user
          predicates:
          - Path=/users/**