

#Host Port
server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/  

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-product
          uri: lb://product
          predicates:
            - Path=/products/**
        - id: service-user
          uri: lb://user
          predicates:
            - Path=/users/**


