
server:
    port: 8081


spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jose-david-lara/vega.git
          searchPaths: config-data
          username: "jose.david.lara@hotmail.com"
          password: "Joselara007"
          default-label: "master"
  security:
    user:
      name: root
      password: s3cr3t
            